### ISSUE TITLE
Fields with persisted == false are annotated with @JsonProperty in the corresponding bean class

### ISSUE THREAD

**Issue by killergerbah** [N3TWORK/dynamap#67]
This can cause Jackson to attempt to deserialize such fields out of the field loaded from Dynamo DB which may result in exceptions like the following:
```
! java.lang.IllegalArgumentException: Conflicting setter definitions for property "consumedCapacity": com.n3twork.dynamap.DynamoRateLimiter#setConsumedCapacity(java.util.List) vs com.n3twork.dynamap.DynamoRateLimiter#setConsumedCapacity(com.amazonaws.services.dynamodbv2.model.ConsumedCapacity)
! at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:512)
! at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getPrimaryType(POJOPropertyBuilder.java:353)
! at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getRawPrimaryType(POJOPropertyBuilder.java:373)
! at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:709)
! at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:559)
! at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:277)
! at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
! ... 84 common frames omitted
! Causing: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "consumedCapacity": com.n3twork.dynamap.DynamoRateLimiter#setConsumedCapacity(java.util.List) vs com.n3twork.dynamap.DynamoRateLimiter#setConsumedCapacity(com.amazonaws.services.dynamodbv2.model.ConsumedCapacity)
!  at [Source: UNKNOWN; line: -1, column: -1]
! at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:302)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:268)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
! at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
! at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:581)
! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
! at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
! at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:558)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:188)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:28)
! at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:765)
! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:550)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
! at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
! at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
! at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:591)
! at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4733)
! at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4307)
! ... 66 common frames omitted
! Causing: java.lang.IllegalArgumentException: Conflicting setter definitions for property "consumedCapacity": com.n3twork.dynamap.DynamoRateLimiter#setConsumedCapacity(java.util.List) vs com.n3twork.dynamap.DynamoRateLimiter#setConsumedCapacity(com.amazonaws.services.dynamodbv2.model.ConsumedCapacity)
!  at [Source: UNKNOWN; line: -1, column: -1]
! at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4314)
! at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4245)
! at com.n3twork.dynamap.DynamapBeanFactory.asDynamapBean(DynamapBeanFactory.java:33)
! at com.n3twork.dynamap.DynamapLoadService.loadItem(DynamapLoadService.java:92)
! at com.n3twork.dynamap.Dynamap.batchGetObject(Dynamap.java:387)```

**Comment by killergerbah** [comment]
This issue does not occur when `serialized` is set to false.

**Comment by nanreh** [comment]
Just a follow up since I ran into this too, the key to add to the attribute in the Dynamap JSON is `serialize: false` (no `d` at the end).
